### ISSUE TITLE
Incorrect mesh color

### ISSUE THREAD

**Issue by luoliawow** [zju-bmi-lab/SpikingGS#2]
Dear Authors,

Thanks for your intresting work. While I try to reproduce your work, I found the gaussian point cloud could be correctly displayed while the extracted mesh got incorrect color, which I also encountered in 2DGS. Here're the meshes, first shot is the point cloud visualization via [this site](https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php), and the other one is the extracted mesh.

Could you give any suggestion for these weird results? 

FYI, my environment was using python3.8, torch2.0.1+cu118 and the latest(since 0.9.0.0 not supported in python3.8) open3d. No code and parameters changes for the script `full_eval_dtu.sh`, but replacing `o3d.integration` to `o3d.pipelines.integration` in `render_tsdf.py` due to the changing open3d API.

Looking forward to your reply and many thanks in advance.

![spgs_vis](https://github.com/user-attachments/assets/4c4353f9-fc4a-4699-8513-1b7ca94542a9)
![spgs](https://github.com/user-attachments/assets/cd4d1212-55f0-4622-9d6d-9b3fafc17f33)

**Comment by LMozart** [comment]
Hi, thank you for your interest. This issue may stem from the conversion of spherical harmonics (SH) functions to mesh colors. The color of rendered image or our target of accurate 3D geometry will not be affected—only the mesh colors are impacted. As you mentioned, this seems to be a common issue in other GS-based methods. One possibility is that, due to the lack of constraints on Gaussians' colors during training, negative values might occur. This may cause the color distortions on the mesh. Extra efforts may be necessary if mesh color is important for your downstream applications.
